### ISSUE TITLE
Create Testing Visualizations

### ISSUE THREAD

**Issue by joel-oe-lacey** [codefordenver/cdphe-accessible-covid19#23]
## Overview
The Dashboard we are replicating has a visualization set pertaining to Testing:
https://covid19.colorado.gov/data

Testing information can be found in some capacity from almost all the endpoints, run through them when brainstorming visualizations to try to determine the best fit:
https://data-cdphe.opendata.arcgis.com/search?tags=covid19

What sort of visualization can we create here? Either a like-for-like recreation or something equivalent is great, or is there an opportunity for greater granularity?

### This issue involves:

1. Running through the API data to see what is available
2. Choosing a visualization to attempt to create
3. Creating a new component for that visualization
4. Fetching the data
5. Rendering the visualization in Semiotic

Feel free to reach out for brainstorming. The more you can focus on creating with accessibility as a primary focus, the less refactoring has to be done, so it's an important design configuration that would be great to handle upfront as much as possible.

**Comment by galbwe** [comment]
Going to start with replicating the total pcr tests bar plot part of this graph: 
![Screen Shot 2021-01-16 at 1 18 10 PM](https://user-images.githubusercontent.com/20004072/104822089-70752580-57fd-11eb-8bf4-87774e52b6cd.png)
Looks like this is the relevant api endpoint
```
https://services3.arcgis.com/66aUo8zsujfVXRIT/arcgis/rest/services/colorado_covid19_laboratory_positivity_data/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json
```
although I might have to play around with the query parameters because as is this endpoint returns way more data than needed for a single visualization.

**Comment by galbwe** [comment]
@joel-oe-lacey what are your thoughts on also adding a table representation of this graph to improve accessibility? Might have to aggregate the number of tests by month to keep the table manageable.

**Comment by joel-oe-lacey** [comment]
Hey @galbwe,

Thanks for picking this one up! I would say that would be a good backup route if we can't add accessibility effectively to semiotic, otherwise it might be a bit of unneeded redundancy and you could save yourself some work there.

I'm going to attempt to make the graphs we currently have more accessible in the next few days and I can let you know how that goes, if it looks like a lost cause maybe we could tac that on. 

In terms of aggregation, feel free to take license as to whatever creates the most consumable data set I'd say. Let me know how you get on!

**Comment by galbwe** [comment]
@joel-oe-lacey I opened a PR for this one. I made some changes to the component structure. In particular, I made the Card component take a `children` prop so it can display different kinds of visualizations. I also got rid of the `DailyStats` component for now because the two different kinds of visualizations needed different data to be passed through props. If you want, I can try bringing it back and refactor the contents of the individual cards into instances of `DailyStats`.

**Comment by galbwe** [comment]
Also didn't focus too much on accessibility, besides adjusting the colors. If there are changes I could make based on your research in the other cards, I'll be happy to add them.

**Comment by joel-oe-lacey** [comment]
Sorry for the delay here @galbwe, I've been caught up in some interview prep for the week. I took an initial run through and this looks fantastic! I'm still working on getting accessibility in place for the charts generally, it looks like something a bit more custom might need to be built there so hopefully once that is worked out we can just hook that in with this change without too much trouble.

I should have time tomorrow to go through the PR in its entirety and merge it in. Thanks so much for building that out.

**Comment by joel-oe-lacey** [comment]
These ended up coming together great! Thanks so much for all your help here @galbwe.
